### ISSUE TITLE
xygrib for Raspbian Buster

### ISSUE THREAD

**Issue by sailoog** [openplotter/pi-gen#1]
ping @free-x
I am trying to update openplotter pi-gen to the new rasbian based on debian buster and the package libproj12 does not exist in buster. Now is libproj13. Do you have plans to update your deb soon? Thanks

**Comment by free-x** [comment]
pong @sailoog,

somehow raspberry foundation caught me on the wrong foot with the announcement to switch to Buster. I don't have a Buster build chain for armhf platform yet. With amd64 this works fine. I'll build a chroot for Buster and get back to you. asap.

Another thing: I see that you want to use "xenial" packages for buster. Wouldn't it be better to use the "bionic" packages? 

Greetings
free-x

**Comment by sailoog** [comment]
ping @free-x 

Yes, raspberry guys caught all of us :)
OK, do not stress, it is not urgent.

We have changed to bionic too but I think it is not uploaded to github yet. These are the new packages:
https://launchpad.net/~openplotter/+archive/ubuntu/openplotter

Thanks!

**Comment by free-x** [comment]
pong @sailoog 

try these 2 packages
https://www.free-x.de/raspbian/buster/xygrib_1.2.5-20190625_armhf.deb
https://www.free-x.de/raspbian/buster/xygrib-maps_1.2.5-20190625_all.deb

Regards
free-x

**Comment by sailoog** [comment]
ping @free-x 
it works! I will add these packages to openplotter-pi-gen. Thanks!

**Comment by free-x** [comment]
ping @sailoog 
release 1.2.6 is now available
https://www.free-x.de/raspbian/buster/xygrib-maps_1.2.6-1_all.deb
https://www.free-x.de/raspbian/buster/xygrib_1.2.6-1_armhf.deb

regards
free-x

**Comment by sailoog** [comment]
done, thanks!
